export const SET_ACTIVE_ROUTE = 'SET_ACTIVE_ROUTE'
export const SET_ACTIVE_PROPERTY = 'SET_ACTIVE_PROPERTY'
export const REQUEST_ROUTES_PENDING = 'REQUEST_ROUTES_PENDING'
export const REQUEST_ROUTES_SUCCESS = 'REQUEST_ROUTES_SUCCESS'
export const REQUEST_ROUTES_FAILED = 'REQUEST_ROUTES_FAILED'

export const GET_DRIVERS_PENDING = 'GET_DRIVERS_PENDING'
export const GET_DRIVERS_SUCCESS = 'GET_DRIVERS_SUCCESS'
export const GET_DRIVERS_FAILED = 'GET_DRIVERS_FAILED'
export const SET_DRIVER_NAME = 'SET_DRIVER_NAME'

export const UPDATE_ADDRESSES_PENDING = 'UPDATE_ADDRESSES_PENDING'
export const UPDATE_ADDRESSES_SUCCESS = 'UPDATE_ADDRESSES_SUCCESS'
export const UPDATE_ADDRESSES_FAILED = 'UPDATE_ADDRESSES_FAILED'

export const GET_ROUTE_PROPERTIES_SUCCESS = 'GET_ROUTE_PROPERTIES_SUCCESS'
export const FILTER_PROPERTIES_SUCCESS = 'FILTER_PROPERTIES_SUCCESS'

export const GET_ROUTE_SUCCESS = 'GET_ROUTE_SUCCESS'
export const GET_ROUTE_PENDING = 'GET_ROUTE_PENDING'
export const GET_ROUTE_FAILED = 'GET_ROUTE_FAILED'

export const SAVE_ROUTE_SUCCESS = 'SAVE_ROUTE_SUCCESS'
export const SAVE_ROUTE_PENDING = 'SAVE_ROUTE_PENDING'
export const SAVE_ROUTE_FAILED = 'SAVE_ROUTE_FAILED' 

export const NEW_PROPERTY_SUCCESS = 'NEW_PROPERTY_SUCCESS'
export const NEW_PROPERTY_PENDING = 'NEW_PROPERTY_PENDING'
export const NEW_PROPERTY_FAILED = 'NEW_PROPERTY_FAILED'

export const DEL_PROPERTY_SUCCESS = 'DEL_PROPERTY_SUCCESS'
export const DEL_PROPERTY_PENDING = 'DEL_PROPERTY_PENDING'
export const DEL_PROPERTY_FAILED = 'DEL_PROPERTY_FAILED'

export const SHOW_ROUTE_EDITOR = 'SHOW_ROUTE_EDITOR'

export const SHOW_ROUTE = 'SHOW_ROUTE'

export const SET_TRACTOR_NAME = 'SET_TRACTOR_NAME'
export const GET_TRACTORS_PENDING = 'GET_TRACTORS_PENDING'
export const GET_TRACTORS_SUCCESS = 'GET_TRACTORS_SUCCESS'
export const GET_TRACTORS_FAILED = 'GET_TRACTORS_FAILED'

export const GET_VEHICLE_TYPES_PENDING = "GET_VEHICLE_TYPES_PENDING"
export const GET_VEHICLE_TYPES_SUCCESS = "GET_VEHICLE_TYPES_SUCCESS"
export const GET_VEHICLE_TYPES_FAILED = "GET_VEHICLE_TYPES_FAILED"

export const ROUTE_DATA_PENDING = 'ROUTE_DATA_PENDING'
export const ROUTE_DATA_SUCCESS = 'ROUTE_DATA_SUCCESS'
export const ROUTE_DATA_FAILED = 'ROUTE_DATA_FAILED'
