export const SET_ACTIVE_ROUTE = 'SET_ACTIVE_ROUTE'

export const REQUEST_ROUTES_PENDING = 'REQUEST_ROUTES_PENDING'
export const REQUEST_ROUTES_SUCCESS = 'REQUEST_ROUTES_SUCCESS'
export const REQUEST_ROUTES_FAILED = 'REQUEST_ROUTES_FAILED'

export const SET_DRIVER_NAME = 'SET_DRIVER_NAME'

export const REQUEST_ADDRESSES_PENDING = 'REQUEST_ADDRESSES_PENDING'
export const REQUEST_ADDRESSES_SUCCESS = 'REQUEST_ADDRESSES_SUCCESS'
export const REQUEST_ADDRESSES_FAILED = 'REQUEST_ADDRESSES_FAILED'