export const SET_ACTIVE_ROUTE = 'SET_ACTIVE_ROUTE'
export const SET_ACTIVE_PROPERTY = 'SET_ACTIVE_PROPERTY'
export const REQUEST_ROUTES_PENDING = 'REQUEST_ROUTES_PENDING'
export const REQUEST_ROUTES_SUCCESS = 'REQUEST_ROUTES_SUCCESS'
export const REQUEST_ROUTES_FAILED = 'REQUEST_ROUTES_FAILED'

export const SET_DRIVER_NAME = 'SET_DRIVER_NAME'

export const REQUEST_ADDRESSES_PENDING = 'REQUEST_ADDRESSES_PENDING'
export const REQUEST_ADDRESSES_SUCCESS = 'REQUEST_ADDRESSES_SUCCESS'
export const REQUEST_ADDRESSES_FAILED = 'REQUEST_ADDRESSES_FAILED'

export const GET_ROUTE_PROPERTIES_SUCCESS = 'GET_ROUTE_PROPERTIES_SUCCESS'

export const GET_ROUTE_SUCCESS = 'GET_ROUTE_SUCCESS'
export const GET_ROUTE_PENDING = 'GET_ROUTE_PENDING'
export const GET_ROUTE_FAILED = 'GET_ROUTE_FAILED'

export const SAVE_ROUTE_SUCCESS = 'SAVE_ROUTE_SUCCESS'
export const SAVE_ROUTE_PENDING = 'SAVE_ROUTE_PENDING'
export const SAVE_ROUTE_FAILED = 'SAVE_ROUTE_FAILED' 

export const SHOW_ROUTE_EDITOR = 'SHOW_ROUTE_EDITOR'

export const SHOW_ROUTE = 'SHOW_ROUTE'

